name: Trigger auto deployment for container-app-ulix3tt7bxejm

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-ulix3tt7bxejm-AutoDeployTrigger-9ea65353-78a1-4fd5-93b1-b993404e0c5c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPULIX3TT7BXEJM_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPULIX3TT7BXEJM_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPULIX3TT7BXEJM_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPULIX3TT7BXEJM_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPULIX3TT7BXEJM_REGISTRY_PASSWORD }}
          containerAppName: container-app-ulix3tt7bxejm
          resourceGroup: todonodecorporate365a1d7
          imageToBuild: default/container-app-ulix3tt7bxejm:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


